"use client";
import {useEffect,useRef} from "react";
const phone="541151399549";
const wa=`https://wa.me/${phone}?text=${encodeURIComponent("Hola Mia, vi tu portfolio y quiero contarte una idea.")}`;
const waFor=(service:string)=>`https://wa.me/${phone}?text=${encodeURIComponent(`Hola Mia, quisiera consultar por ${service}.`)}`;
const WhatsAppIcon=()=> <svg className="mfWa" viewBox="0 0 24 24" aria-hidden="true"><path d="M12.04 2a9.84 9.84 0 0 0-8.5 14.78L2 22l5.35-1.49A9.93 9.93 0 1 0 12.04 2Zm0 17.98a8.1 8.1 0 0 1-4.13-1.13l-.3-.18-3.18.88.85-3.1-.2-.32a8.07 8.07 0 1 1 6.96 3.85Zm4.43-6.05c-.24-.12-1.44-.71-1.66-.79-.22-.08-.38-.12-.55.12-.16.24-.62.79-.76.95-.14.16-.28.18-.52.06-.24-.12-1.03-.38-1.96-1.21-.72-.65-1.21-1.44-1.35-1.69-.14-.24-.02-.37.1-.49.11-.11.24-.28.36-.42.12-.14.16-.24.24-.41.08-.16.04-.3-.02-.42-.06-.12-.54-1.31-.75-1.79-.2-.47-.4-.4-.55-.41h-.47c-.16 0-.42.06-.65.3-.22.24-.85.83-.85 2.03 0 1.19.87 2.35.99 2.51.12.16 1.71 2.61 4.14 3.66.58.25 1.03.4 1.38.51.58.18 1.11.16 1.53.1.47-.07 1.44-.59 1.64-1.15.2-.57.2-1.05.14-1.15-.06-.1-.22-.16-.46-.28Z"/></svg>;
export default function Home(){
 const menuRef=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(menuRef.current?.open&&!menuRef.current.contains(e.target as Node))menuRef.current.open=false};const escape=(e:KeyboardEvent)=>{if(e.key==="Escape"&&menuRef.current?.open)menuRef.current.open=false};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",escape)}},[]);
 const close=()=>{if(menuRef.current)menuRef.current.open=false};
 return <main className="miaSite">
  <nav className="mfShell mfNav"><a className="mfBrand" href="#inicio"><b>MF</b><span>Mia Fernandez<small>Diseño web con sensibilidad</small></span></a><div className="mfDesktopNav"><a href="#trabajo">Mi trabajo</a><a href="#servicios">Qué puedo crear</a><a href="#proceso">Cómo trabajo</a><a href={wa}>Hablemos <WhatsAppIcon/></a></div><details className="mfMobileNav" ref={menuRef}><summary aria-label="Abrir menú"><i/><i/></summary><div><a href="#trabajo" onClick={close}>Mi trabajo</a><a href="#servicios" onClick={close}>Qué puedo crear</a><a href="#proceso" onClick={close}>Cómo trabajo</a><a href={wa} onClick={close}>Hablemos <WhatsAppIcon/></a></div></details></nav>
  <header className="mfHero mfShell" id="inicio"><div className="mfHeroCopy"><span className="mfEyebrow">DISEÑO DIGITAL · ARGENTINA</span><h1>Ideas bonitas,<br/>sitios que se sienten<br/><em>muy tuyos.</em></h1><p>Creo invitaciones y páginas web delicadas, claras y pensadas para conectar con las personas desde el primer vistazo.</p><div className="mfHeroActions"><a className="mfPrimary" href={wa}>Quiero crear algo <WhatsAppIcon/></a><a href="#trabajo">Conocé mi estilo <span>↓</span></a></div></div><div className="mfMood" aria-label="Composición visual de diseño web"><div className="mfArch"><span>una idea</span><strong>hecha<br/>experiencia</strong><i>✦</i></div><div className="mfMiniCard"><span>01</span><p>Diseño amable</p></div><div className="mfFlower">✿</div><div className="mfNote">Detalles que<br/><b>cuentan historias</b></div></div></header>
  <section className="mfAbout"><div className="mfShell"><span>MI MANERA DE CREAR</span><p>No se trata solamente de que una página se vea linda. Busco que cada color, palabra y movimiento acompañe la historia que querés compartir.</p><div><b>01</b>Escucho tu idea <b>02</b>Encuentro su estilo <b>03</b>La llevo a la web</div></div></section>
  <section className="mfWork mfShell" id="trabajo"><div className="mfSectionHead"><span>PROYECTOS CON HISTORIA</span><h2>Ideas diferentes,<br/><em>experiencias con identidad.</em></h2></div><div className="mfPortfolioList"><a className="mfFeatured" href="https://invitacion-danna.vercel.app/" target="_blank" rel="noreferrer"><div className="mfProjectVisual"><img src="/projects/danna.png" alt="Invitación digital de Danna"/><span>PROYECTO PUBLICADO</span><i>XV</i></div><div className="mfProjectCopy"><small>INVITACIÓN DIGITAL</small><h3>Danna</h3><p>Una invitación delicada que reúne la emoción del evento, la información importante y la confirmación de asistencia en un solo lugar.</p><ul><li>Música</li><li>Galería</li><li>Ubicación</li><li>Confirmación</li></ul><strong>Visitar experiencia <span>↗</span></strong></div></a>
<a className="mfFeatured mfFeaturedAlt" href="https://lumiere-beauty-smoky.vercel.app/" target="_blank" rel="noreferrer"><div className="mfProjectVisual"><img src="/projects/lumiere-beauty.png" alt="Página web de Lumière Beauty"/><span className="mfDevelopment">EN DESARROLLO</span><i>02</i></div><div className="mfProjectCopy"><small>PÁGINA WEB · BELLEZA</small><h3>Lumière Beauty</h3><p>Una experiencia editorial para una marca de belleza, cuidado personal e insumos, diseñada para presentar sus servicios con elegancia y facilitar cada consulta.</p><ul><li>Servicios</li><li>Insumos</li><li>Turnos</li><li>Responsive</li></ul><strong>Ver proyecto en desarrollo <span>↗</span></strong></div></a>
<a className="mfFeatured mfInvitationProject" href="https://invitacion-luna-fawn.vercel.app/" target="_blank" rel="noreferrer"><div className="mfProjectVisual"><img src="/projects/invitacion-rosa.png" alt="Invitación digital de Luna"/><span>PROYECTO PUBLICADO</span><i>03</i></div><div className="mfProjectCopy"><small>INVITACIÓN DIGITAL · XV AÑOS</small><h3>Luna</h3><p>Una experiencia envolvente con apertura interactiva, detalles brillantes y una estética delicada pensada para anunciar una noche inolvidable.</p><ul><li>Apertura interactiva</li><li>Música</li><li>Cuenta regresiva</li><li>RSVP</li></ul><strong>Visitar experiencia <span>↗</span></strong></div></a>
</div></section>
  <section className="mfServices" id="servicios"><div className="mfShell"><div className="mfSectionHead"><span>QUÉ PUEDO CREAR</span><h2>Dos caminos,<br/><em>infinitas posibilidades.</em></h2></div><div className="mfServiceGrid"><a href={waFor("una invitación digital")}><span>01 · MOMENTOS</span><div className="mfServiceIcon">✿</div><h3>Invitaciones digitales</h3><p>Para cumpleaños, XV, bodas y celebraciones que merecen una presentación especial.</p><ul><li>Cuenta regresiva y música</li><li>Galería, mapa y RSVP</li><li>Diseño adaptado a celulares</li></ul><strong>Consultar <WhatsAppIcon/></strong></a><a href={waFor("una página web")}><span>02 · PROYECTOS</span><div className="mfServiceIcon">⌁</div><h3>Páginas web</h3><p>Para emprendimientos y personas que necesitan mostrar lo que hacen con claridad y personalidad.</p><ul><li>Presentación de servicios</li><li>Catálogos y contacto</li><li>Experiencia responsive</li></ul><strong>Consultar <WhatsAppIcon/></strong></a></div></div></section>
  <section className="mfProcess mfShell" id="proceso"><div className="mfSectionHead"><span>UN PROCESO CERCANO</span><h2>De tu mundo<br/><em>a una página propia.</em></h2></div><div className="mfJourney"><article><b>01</b><small>NOS CONOCEMOS</small><h3>Me contás</h3><p>Charlamos sobre tu idea, lo que imaginás y aquello que querés transmitir.</p></article><article><b>02</b><small>LE DAMOS FORMA</small><h3>Te propongo</h3><p>Armo una dirección visual y ordeno el contenido para que todo tenga sentido.</p></article><article><b>03</b><small>LA HACEMOS REAL</small><h3>La creamos</h3><p>Desarrollo, ajustamos juntas los detalles y dejo tu página lista para compartir.</p></article></div></section>
  <section className="mfClosing mfShell"><div><span>¿TENÉS ALGO EN MENTE?</span><h2>Tu idea puede ser<br/><em>la próxima historia.</em></h2><p>No hace falta que tengas todo resuelto. Contame lo que imaginás y pensamos juntas el mejor comienzo.</p></div><aside><a href={wa}>Escribime por WhatsApp <WhatsAppIcon/></a><a className="mfEmailLink" href="mailto:quimey138@gmail.com">quimey138@gmail.com <span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 6.5h17v11h-17z"/><path d="m4.5 7.5 7.5 5.6 7.5-5.6"/></svg></span></a><small>Respuesta personal · Presupuesto a medida</small></aside></section>
  <footer className="mfFooter mfShell"><span>© 2026 Mia Fernandez</span><span>Invitaciones & páginas web</span><a href="mailto:quimey138@gmail.com">quimey138@gmail.com</a></footer>
 </main>}
